config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :cart_items
  resources :carts, except: :show
  get 'cart', to: 'carts#show', as: 'session_cart'

  resources :items

  root to: 'catalog#index', as: 'catalog'

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :cart_items

  before_destroy :ensure_not_referenced_by_any_cart_item

  validates :name, :desc, :img_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :name, uniqueness: true
  validates :img_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|jpeg|png)\Z}i,
    message: 'Allowed formats: GIF, JPG, PNG'
            # Разрешенные форматы изображений: GIF, JPG и PNG
  }

  private
    def ensure_not_referenced_by_any_cart_item
      if cart_items.empty?
        return true
      else
        errors.add(:base, 'В корзине есть товары!')
        return false
      end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Товар создан.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Товар обновлен.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Товар удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :desc, :img_url, :price)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc, rows: 5 %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit 'Сохранить' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Изменение товара</h1>

<%= render 'form' %>

<%= link_to 'Показать', @item %> |
<%= link_to 'Назад', items_path %>

app/views/items/index.html.erb
<h1>Товары</h1>

<table>
<% @items.each do |item| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td>
      <%= image_tag(item.img_url, class: 'list_img') %>
    </td>
    <td class="list_desc">
      <dl>
        <dt><%= item.name %></dt>
        <dd><%= truncate(strip_tags(item.desc), length: 80) %></dd>
      </dl>
    </td>
    <td class="list_acts">
      <%= link_to 'Показать', item %><br/>
      <%= link_to 'Изменить', edit_item_path(item) %><br/>
      <%= link_to 'Удалить', item, method: :delete, data: { confirm: 'Вы уверены?' } %>
    </td>
  </tr>
  <% end %>
</table>

<br>

<%= link_to 'Новый товар', new_item_path %>

app/views/items/new.html.erb
<h1>Новый товар</h1>

<%= render 'form' %>

<%= link_to 'Назад', items_path %>

app/views/items/show.html.erb
<table>
  <tr>
    <td><strong>Наименование</strong></td>
    <td><strong>Описание</strong></td>
    <td><strong>Изображение</strong></td>
    <td><strong>Цена</strong></td>
  </tr>
  <tr>
    <td><%= @item.name %></td>
    <td><%= @item.desc %></td>
    <td><%= image_tag(@item.img_url, class: 'list_img') %></td>
    <td><%= @item.price %></td>
  </tr>
</table>

<%= link_to 'Изменить', edit_item_path(@item) %> |
<%= link_to 'Назад', items_path %>